# Wanderings through duckdb and polars

Findings: 
1. gosh this duckdb and polars stuff is fast.
2. now we get to figure out the useful views we need and we can work on the fast because parquet has modern bindings in so many places, from R to python.

In [1]:
import duckdb 
import polars as pl
from pathlib import Path

In [2]:
print("duckDB Version =", duckdb.__version__)
print("Polars Build Info =", pl.build_info())
print("Polars Thread Pool Size =", pl.thread_pool_size())

duckDB Version = 1.5.6
Polars Build Info = {'version': '1.44.2'}
Polars Thread Pool Size = 8

In [3]:
# Various paths to data sets in the repo

NATIONAL_CSB_PARQUET_PATH = Path("../out/national1825.parquet")
CSB_LAND_COVER_CODES_PARQUET_PATH = Path("../useful-views/land_cover_codes.parquet")

In [4]:
national = None
national = duckdb.connect()
national.execute("LOAD spatial")

In [5]:
# Excluding `Shape` as that is a multipolygon column.
# It is not easily rendered and not needed for this example.

"""
Also note, displaying this on your local (VS Code) should be pretty easy, but displaying on github through the  
html render of the notebook may require that your browser is gigantically wide, or text super small. 
On my 27 inch display its readable, but I for sure have my glasses on :) 

"""

national.sql(
    """
    SELECT * EXCLUDE Shape
    FROM read_parquet($path)
    LIMIT 20
    """,
    params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
).show()

┌──────────┬─────────────────┬──────────┬────────────────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────────┬──────────┬─────────┬─────────┬──────────┬───────────────────┬──────────────┬──────────┬────────────────────┬────────────────────┐
│ OBJECTID │      CSBID      │ CSBYEARS │      CSBACRES      │ CDL2018 │ CDL2019 │ CDL2020 │ CDL2021 │ CDL2022 │ CDL2023 │ CDL2024 │ CDL2025 │ STATEFIPS │ STATEASD │   ASD   │  CNTY   │ CNTYFIPS │     INSIDE_X      │   INSIDE_Y   │ ORIG_FID │    Shape_Length    │     Shape_Area     │
│  int64   │     varchar     │ varchar  │       double       │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  varchar  │ varchar  │ varchar │ varchar │ varchar  │      double       │    double    │  int32   │       double       │       double       │
├──────────┼─────────────────┼──────────┼────────────────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┼─────────┼──────────┼───────────────────┼──────────────┼──────────┼────────────────────┼────────────────────┤
│        1 │ 351825000000001 │ 1825     │  8.014266533798391 │      24 │      24 │      24 │      24 │      24 │       4 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -648193.3343 │ 1447136.6069 │     NULL │ 1094.6718033936615 │  32432.71572386057 │
│        2 │ 351825000000002 │ 1825     │  5.775874123460195 │      24 │      24 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647571.4914 │ 1447063.6498 │     NULL │ 1164.5374695384517 │ 23374.226788312517 │
│        3 │ 351825000000003 │ 1825     │  5.206379494043526 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -647642.659499999 │ 1446862.2847 │     NULL │  760.5431722642115 │ 21069.554571055713 │
│        4 │ 351825000000004 │ 1825     │  50.28417034104927 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │       -647922.047 │ 1447089.7116 │     NULL │ 2879.6399849775394 │  203493.6316634435 │
│        5 │ 351825000000005 │ 1825     │  24.59281108363644 │      24 │     152 │     152 │     152 │     152 │     152 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -650354.5561 │  1447147.379 │     NULL │  2484.031587754646 │  99523.97357418023 │
│        6 │ 351825000000006 │ 1825     │ 15.679465761062357 │      24 │      27 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647712.9946 │ 1446712.4585 │     NULL │ 1263.8151571928627 │  63452.80052590439 │
│        7 │ 351825000000007 │ 1825     │  5.626245857159946 │      24 │      27 │      24 │      24 │      27 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -648253.426999999 │ 1446722.3124 │     NULL │  915.4634275197637 │ 22768.700255759068 │
│        8 │ 351825000000008 │ 1825     │ 11.182568883345644 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -648139.9377 │ 1446656.0112 │     NULL │ 1218.8649740104102 │ 45254.431722043584 │
│        9 │ 351825000000009 │ 1825     │ 32.228273218168056 │      24 │      24 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -647989.902000001 │ 1446581.1281 │     NULL │  3108.090986523694 │  130423.7161501482 │
│       10 │ 351825000000010 │ 1825     │  7.615022137490359 │      24 │      27 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647622.9641 │ 1446542.7175 │     NULL │  959.5328921666119 │ 30817.024511795815 │
│       11 │ 351825000000011 │ 1825     │    8.4254842883058 │      24 │      24 │       4 │      61 │      61 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │      -663694.4246 │ 1446796.6361 │     NULL │ 1249.2550179985221 │  34096.86159127059 │
│       12 │ 351825000000012 │ 1825     │  7.636054494485669 │      24 │      28 │       4 │      61 │      61 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │      -664305.4913 │ 1446537.7011 │     NULL │  888.6102933662967 │  30902.13978124123 │
│       13 │ 351825000000013 │ 1825     │ 12.473350977786481 │      24 │      24 │       4 │      36 │      61 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │ -664126.719799999 │ 1446669.4861 │     NULL │ 1451.8925633338038 │  50478.06242535233 │
│       14 │ 351825000000014 │ 1825     │  4.447652374056347 │      24 │       4 │       4 │     152 │      61 │      24 │     176 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │ -663735.160800001 │ 1446633.0692 │     NULL │  722.0219785720816 │ 17999.082570810824 │
│       15 │ 351825000000015 │ 1825     │ 14.712819560700877 │      24 │      24 │     176 │      61 │      61 │       4 │     152 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │ -664225.608899999 │ 1446227.8119 │     NULL │ 1689.0843344901873 │   59540.9064942225 │
│       16 │ 351825000000016 │ 1825     │ 10.585111126880049 │      24 │      24 │       4 │      61 │      61 │       4 │     152 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │      -664240.7382 │ 1446078.3603 │     NULL │ 1268.9492650310676 │  42836.59629184605 │
│       17 │ 351825000000017 │ 1825     │  75.70278063432691 │      24 │      24 │       4 │      61 │      61 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │ -663838.132999999 │ 1446315.8669 │     NULL │  4861.384264784512 │ 306359.50944037654 │
│       18 │ 351825000000018 │ 1825     │  4.747859440044032 │      24 │       4 │       4 │      61 │      61 │     152 │     152 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │ -663657.830499999 │ 1445930.2454 │     NULL │  614.5588465888663 │ 19213.982323447097 │
│       19 │ 351825000000019 │ 1825     │ 13.414138168936097 │      24 │       4 │       4 │      61 │      61 │       4 │     152 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │ -664243.201400001 │  1445851.326 │     NULL │ 1115.2090913032357 │  54285.30834093624 │
│       20 │ 351825000000020 │ 1825     │  7.156940174482495 │      24 │      24 │     176 │      61 │      61 │     152 │     152 │     152 │ 35        │ 3530     │ 30      │ Harding │ 021      │ -664018.183599999 │  1445751.204 │     NULL │  878.7855385263255 │ 28963.225162621857 │
└──────────┴─────────────────┴──────────┴────────────────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────────┴──────────┴─────────┴─────────┴──────────┴───────────────────┴──────────────┴──────────┴────────────────────┴────────────────────┘
  20 rows                                                                                                                                                                                                                                                                       22 columns

In [6]:

# if controlled out of the notebook flow - uncomment to see the nature of the multipolygon.

if 0:
    national.sql(
        """
        SELECT Shape
        FROM read_parquet($path)
        LIMIT 20
        """,
        params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
    ).show()

In [7]:
shape_sample = None
shape_sample = national.sql(
    """
    SELECT ST_AsText(Shape) AS Shape
    FROM read_parquet($path)
    LIMIT 20
    """,
    params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
).pl().slice(17, 1)

#just to give the reader a sense of the specific shape at this position...

In [8]:
print(shape_sample)

shape: (1, 1)
┌─────────────────────────────────┐
│ Shape                           │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ MULTIPOLYGON (((-663619.003499… │
└─────────────────────────────────┘

In [9]:
csb_codes = None
csb_codes = duckdb.connect()
csb_codes.execute("LOAD spatial")

In [10]:
csb_codes.sql(
    """
    SELECT *
    FROM read_parquet($path)
    LIMIT 20
    """,
    params={"path": str(CSB_LAND_COVER_CODES_PARQUET_PATH)},
)

┌─────────────────┬──────────────────────────┐
│ land_cover_code │     land_cover_name      │
│      int64      │         varchar          │
├─────────────────┼──────────────────────────┤
│               0 │ Background               │
│               1 │ Corn                     │
│               2 │ Cotton                   │
│               3 │ Rice                     │
│               4 │ Sorghum                  │
│               5 │ Soybeans                 │
│               6 │ Sunflower                │
│              10 │ Peanuts                  │
│              11 │ Tobacco                  │
│              12 │ Sweet Corn               │
│              13 │ Pop or Orn Corn          │
│              14 │ Mint                     │
│              21 │ Barley                   │
│              22 │ Durum Wheat              │
│              23 │ Spring Wheat             │
│              24 │ Winter Wheat             │
│              25 │ Other Small Grains       │
│              26 │ Dbl Crop WinWht/Soybeans │
│              27 │ Rye                      │
│              28 │ Oats                     │
└─────────────────┴──────────────────────────┘
  20 rows                          2 columns

In [12]:
csb_field_year = None
csb_field_year = national.sql(
    """
    SELECT * EXCLUDE Shape
    FROM read_parquet($path)
    LIMIT 10
    """,
    params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
).show()

┌──────────┬─────────────────┬──────────┬────────────────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────────┬──────────┬─────────┬─────────┬──────────┬───────────────────┬──────────────┬──────────┬────────────────────┬────────────────────┐
│ OBJECTID │      CSBID      │ CSBYEARS │      CSBACRES      │ CDL2018 │ CDL2019 │ CDL2020 │ CDL2021 │ CDL2022 │ CDL2023 │ CDL2024 │ CDL2025 │ STATEFIPS │ STATEASD │   ASD   │  CNTY   │ CNTYFIPS │     INSIDE_X      │   INSIDE_Y   │ ORIG_FID │    Shape_Length    │     Shape_Area     │
│  int64   │     varchar     │ varchar  │       double       │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  varchar  │ varchar  │ varchar │ varchar │ varchar  │      double       │    double    │  int32   │       double       │       double       │
├──────────┼─────────────────┼──────────┼────────────────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┼─────────┼──────────┼───────────────────┼──────────────┼──────────┼────────────────────┼────────────────────┤
│        1 │ 351825000000001 │ 1825     │  8.014266533798391 │      24 │      24 │      24 │      24 │      24 │       4 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -648193.3343 │ 1447136.6069 │     NULL │ 1094.6718033936615 │  32432.71572386057 │
│        2 │ 351825000000002 │ 1825     │  5.775874123460195 │      24 │      24 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647571.4914 │ 1447063.6498 │     NULL │ 1164.5374695384517 │ 23374.226788312517 │
│        3 │ 351825000000003 │ 1825     │  5.206379494043526 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -647642.659499999 │ 1446862.2847 │     NULL │  760.5431722642115 │ 21069.554571055713 │
│        4 │ 351825000000004 │ 1825     │  50.28417034104927 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │       -647922.047 │ 1447089.7116 │     NULL │ 2879.6399849775394 │  203493.6316634435 │
│        5 │ 351825000000005 │ 1825     │  24.59281108363644 │      24 │     152 │     152 │     152 │     152 │     152 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -650354.5561 │  1447147.379 │     NULL │  2484.031587754646 │  99523.97357418023 │
│        6 │ 351825000000006 │ 1825     │ 15.679465761062357 │      24 │      27 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647712.9946 │ 1446712.4585 │     NULL │ 1263.8151571928627 │  63452.80052590439 │
│        7 │ 351825000000007 │ 1825     │  5.626245857159946 │      24 │      27 │      24 │      24 │      27 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -648253.426999999 │ 1446722.3124 │     NULL │  915.4634275197637 │ 22768.700255759068 │
│        8 │ 351825000000008 │ 1825     │ 11.182568883345644 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -648139.9377 │ 1446656.0112 │     NULL │ 1218.8649740104102 │ 45254.431722043584 │
│        9 │ 351825000000009 │ 1825     │ 32.228273218168056 │      24 │      24 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -647989.902000001 │ 1446581.1281 │     NULL │  3108.090986523694 │  130423.7161501482 │
│       10 │ 351825000000010 │ 1825     │  7.615022137490359 │      24 │      27 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647622.9641 │ 1446542.7175 │     NULL │  959.5328921666119 │ 30817.024511795815 │
└──────────┴─────────────────┴──────────┴────────────────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────────┴──────────┴─────────┴─────────┴──────────┴───────────────────┴──────────────┴──────────┴────────────────────┴────────────────────┘
  10 rows                                                                                                                                                                                                                                                                       22 columns

In [13]:
national.sql(
    """
    SELECT * EXCLUDE Shape
    FROM read_parquet($path)
    LIMIT 200
    """,
    params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
).show()

┌──────────┬─────────────────┬──────────┬────────────────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────────┬──────────┬─────────┬─────────┬──────────┬───────────────────┬──────────────┬──────────┬────────────────────┬────────────────────┐
│ OBJECTID │      CSBID      │ CSBYEARS │      CSBACRES      │ CDL2018 │ CDL2019 │ CDL2020 │ CDL2021 │ CDL2022 │ CDL2023 │ CDL2024 │ CDL2025 │ STATEFIPS │ STATEASD │   ASD   │  CNTY   │ CNTYFIPS │     INSIDE_X      │   INSIDE_Y   │ ORIG_FID │    Shape_Length    │     Shape_Area     │
│  int64   │     varchar     │ varchar  │       double       │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  varchar  │ varchar  │ varchar │ varchar │ varchar  │      double       │    double    │  int32   │       double       │       double       │
├──────────┼─────────────────┼──────────┼────────────────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┼─────────┼──────────┼───────────────────┼──────────────┼──────────┼────────────────────┼────────────────────┤
│        1 │ 351825000000001 │ 1825     │  8.014266533798391 │      24 │      24 │      24 │      24 │      24 │       4 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -648193.3343 │ 1447136.6069 │     NULL │ 1094.6718033936615 │  32432.71572386057 │
│        2 │ 351825000000002 │ 1825     │  5.775874123460195 │      24 │      24 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647571.4914 │ 1447063.6498 │     NULL │ 1164.5374695384517 │ 23374.226788312517 │
│        3 │ 351825000000003 │ 1825     │  5.206379494043526 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -647642.659499999 │ 1446862.2847 │     NULL │  760.5431722642115 │ 21069.554571055713 │
│        4 │ 351825000000004 │ 1825     │  50.28417034104927 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │       -647922.047 │ 1447089.7116 │     NULL │ 2879.6399849775394 │  203493.6316634435 │
│        5 │ 351825000000005 │ 1825     │  24.59281108363644 │      24 │     152 │     152 │     152 │     152 │     152 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -650354.5561 │  1447147.379 │     NULL │  2484.031587754646 │  99523.97357418023 │
│        6 │ 351825000000006 │ 1825     │ 15.679465761062357 │      24 │      27 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647712.9946 │ 1446712.4585 │     NULL │ 1263.8151571928627 │  63452.80052590439 │
│        7 │ 351825000000007 │ 1825     │  5.626245857159946 │      24 │      27 │      24 │      24 │      27 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -648253.426999999 │ 1446722.3124 │     NULL │  915.4634275197637 │ 22768.700255759068 │
│        8 │ 351825000000008 │ 1825     │ 11.182568883345644 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -648139.9377 │ 1446656.0112 │     NULL │ 1218.8649740104102 │ 45254.431722043584 │
│        9 │ 351825000000009 │ 1825     │ 32.228273218168056 │      24 │      24 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -647989.902000001 │ 1446581.1281 │     NULL │  3108.090986523694 │  130423.7161501482 │
│       10 │ 351825000000010 │ 1825     │  7.615022137490359 │      24 │      27 │      24 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │      -647622.9641 │ 1446542.7175 │     NULL │  959.5328921666119 │ 30817.024511795815 │
│        · │        ·        │  ·       │          ·         │       · │       · │       · │       · │       · │       · │       · │       · │ ·         │  ·       │ ·       │  ·      │  ·       │            ·      │       ·      │       ·  │          ·         │          ·         │
│        · │        ·        │  ·       │          ·         │       · │       · │       · │       · │       · │       · │       · │       · │ ·         │  ·       │ ·       │  ·      │  ·       │            ·      │       ·      │       ·  │          ·         │          ·         │
│        · │        ·        │  ·       │          ·         │       · │       · │       · │       · │       · │       · │       · │       · │ ·         │  ·       │ ·       │  ·      │  ·       │            ·      │       ·      │       ·  │          ·         │          ·         │
│      191 │ 351825000000191 │ 1825     │  18.99500857126066 │      24 │      24 │      24 │      24 │      24 │     205 │      24 │       4 │ 35        │ 3530     │ 30      │ Quay    │ 037      │      -646150.5879 │ 1418870.5858 │     NULL │ 1667.4220053905246 │  76870.37991136141 │
│      192 │ 351825000000192 │ 1825     │ 18.233583277902266 │      24 │      24 │      24 │      24 │     236 │     205 │      24 │       4 │ 35        │ 3530     │ 30      │ Quay    │ 037      │      -645555.5052 │ 1418631.7217 │     NULL │ 1932.8213286510857 │  73788.98874720385 │
│      193 │ 351825000000193 │ 1825     │ 4.5107920961960355 │      24 │      24 │      24 │      24 │      27 │     205 │      24 │       4 │ 35        │ 3530     │ 30      │ Quay    │ 037      │ -645265.523600001 │ 1418563.6682 │     NULL │  747.8420271605578 │ 18254.600982932996 │
│      194 │ 351825000000194 │ 1825     │ 3.3279776958261347 │      24 │      24 │      24 │      24 │      27 │     205 │      24 │      24 │ 35        │ 3530     │ 30      │ Quay    │ 037      │ -645090.708900001 │ 1418534.8312 │     NULL │  636.5761205132334 │ 13467.901783511208 │
│      195 │ 351825000000195 │ 1825     │ 16.820350320652096 │      24 │      24 │      24 │      24 │      27 │     205 │      24 │      36 │ 35        │ 3530     │ 30      │ Quay    │ 037      │ -646048.559599999 │ 1418582.8018 │     NULL │  1529.563825631539 │  68069.81500113655 │
│      196 │ 351825000000196 │ 1825     │  7.177246827187578 │      24 │      24 │      24 │      24 │      27 │     205 │      24 │       4 │ 35        │ 3530     │ 30      │ Quay    │ 037      │ -645786.539000001 │ 1418497.3825 │     NULL │  1001.656311014931 │ 29045.403599252288 │
│      197 │ 351825000000197 │ 1825     │ 12.760722294154478 │      24 │      24 │      24 │      24 │     205 │     205 │      24 │       4 │ 35        │ 3530     │ 30      │ Quay    │ 037      │      -645638.3397 │ 1418478.7953 │     NULL │  1358.398549039222 │  51641.01753442548 │
│      198 │ 351825000000198 │ 1825     │ 117.92076907941153 │      24 │      24 │      24 │      24 │     205 │     205 │      24 │       4 │ 35        │ 3530     │ 30      │ Quay    │ 037      │ -644842.806500001 │ 1418486.6227 │     NULL │  7132.990803983904 │  477210.3305227771 │
│      199 │ 351825000000199 │ 1825     │ 114.01143606497197 │      24 │     205 │      24 │      24 │     205 │     205 │      24 │       4 │ 35        │ 3530     │ 30      │ Quay    │ 037      │      -644458.1599 │ 1418670.4071 │     NULL │  5191.253889136338 │  461389.7578237645 │
│      200 │ 351825000000200 │ 1825     │  44.29686416403955 │      24 │     152 │     152 │     152 │     152 │     152 │     152 │     152 │ 35        │ 3530     │ 30      │ Quay    │ 037      │      -638466.0462 │ 1418066.5476 │     NULL │ 1847.2175345263395 │ 179263.76628877193 │
└──────────┴─────────────────┴──────────┴────────────────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────────┴──────────┴─────────┴─────────┴──────────┴───────────────────┴──────────────┴──────────┴────────────────────┴────────────────────┘
  200 rows (20 shown)                                                                                                                                                                                                                                                           22 columns

In [14]:
csb_field = None
csb_field = national.sql(
    """
    SELECT CSBID, CSBACRES, INSIDE_X, INSIDE_Y, Shape
    FROM read_parquet($path)
    LIMIT 10
    """,
    params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
).show()

┌─────────────────┬────────────────────┬───────────────────┬──────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│      CSBID      │      CSBACRES      │     INSIDE_X      │   INSIDE_Y   │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Shape                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           │
│     varchar     │       double       │      double       │    double    │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  geometry('epsg:5070')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   │
├─────────────────┼────────────────────┼───────────────────┼──────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 351825000000001 │  8.014266533798391 │      -648193.3343 │ 1447136.6069 │ MULTIPOLYGON (((-648233.7895 1447215.1187999994, -648105.5099 1447205.3157000002, -648103.2107999995 1447235.4035, -648071.1411000006 1447232.9530999996, -648076.5052000005 1447162.7481999993, -648108.5753000006 1447165.1986999996, -648137.2260999996 1447106.8610999994, -648144.8900000006 1447006.5687000006, -648225.0666000005 1447012.695699999, -648281.1904000007 1447016.9850999992, -648276.591 1447077.1604999993, -648244.5206000004 1447074.7094, -648239.1549999993 1447144.9141000006, -648271.2251999993 1447147.3652, -648268.9255999997 1447177.4529, -648263.5598000009 1447247.6576000005, -648258.1938000005 1447317.862400001, -648226.1245000008 1447315.4112999998, -648233.7895 1447215.1187999994)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      │
│ 351825000000002 │  5.775874123460195 │      -647571.4914 │ 1447063.6498 │ MULTIPOLYGON (((-647690.9452999998 1446931.5417, -647658.8743999992 1446929.0929000005, -647631.7579999994 1446967.3734000009, -647605.4077000003 1446995.6248000003, -647600.0473999996 1447065.8298000004, -647624.1002999991 1447067.6663000006, -647619.5055999998 1447127.8421, -647592.3900000006 1447166.1228999998, -647560.3199000005 1447163.6743, -647558.0227000006 1447193.7622999996, -647670.2675999999 1447202.3325999994, -647667.2041999996 1447242.4497999996, -647530.9075000007 1447232.0431999993, -647551.5809000004 1446961.2520000003, -647607.7049000002 1446965.5369000006, -647610.7678999994 1446925.4197000004, -647637.1184999999 1446897.1684000008, -647693.2429000009 1446901.4539, -647690.9452999998 1446931.5417)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 │
│ 351825000000003 │  5.206379494043526 │ -647642.659499999 │ 1446862.2847 │ MULTIPOLYGON (((-647551.5809000004 1446961.2520000003, -647554.6436999999 1446921.1348, -647530.5903999992 1446919.2984999996, -647535.1842999998 1446859.1227000002, -647559.2377000004 1446860.9590000007, -647562.3004999999 1446820.8419000003, -647754.7285999991 1446835.5349000003, -647751.6649999991 1446875.6520000007, -647747.0694999993 1446935.8276000004, -647690.9452999998 1446931.5417, -647693.2429000009 1446901.4539, -647637.1184999999 1446897.1684000008, -647610.7678999994 1446925.4197000004, -647607.7049000002 1446965.5369000006, -647551.5809000004 1446961.2520000003)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 │
│ 351825000000004 │  50.28417034104927 │       -647922.047 │ 1447089.7116 │ MULTIPOLYGON (((-647931.7796 1447262.6570999995, -647907.7272999994 1447260.8197000008, -647905.4289999995 1447290.9076000005, -647801.2027000003 1447282.9464999996, -647803.5007000007 1447252.8586, -647771.4309999999 1447250.4092999995, -647747.3785999995 1447248.5724, -647691.2565000001 1447244.2864999995, -647688.9589000009 1447274.3743999992, -647664.9067000002 1447272.5376999993, -647667.2041999996 1447242.4497999996, -647670.2675999999 1447202.3325999994, -647558.0227000006 1447193.7622999996, -647560.3199000005 1447163.6743, -647592.3900000006 1447166.1228999998, -647619.5055999998 1447127.8421, -647624.1002999991 1447067.6663000006, -647600.0473999996 1447065.8298000004, -647605.4077000003 1446995.6248000003, -647631.7579999994 1446967.3734000009, -647658.8743999992 1446929.0929000005, -647690.9452999998 1446931.5417, -647687.8819999993 1446971.6589000002, -647709.6374999993 1447003.5834999997, -647707.3398000002 1447033.6712999996, -647763.4633000009 1447037.9573, -647768.0590000004 1446977.7816000003, -647795.1758999992 1446939.5014999993, -647851.3000000007 1446943.7881000005, -647855.8961999994 1446883.6125000007, -647883.0138000008 1446845.3325999994, -647963.1919999998 1446851.4572, -647965.4904999994 1446821.3695, -648021.6153999995 1446825.6571999993, -648016.2518000007 1446895.8619, -648232.7314999998 1446912.4034000002, -648230.4320999999 1446942.4911000002, -648228.1326000001 1446972.5788000003, -648225.0666000005 1447012.695699999, -648144.8900000006 1447006.5687000006, -648137.2260999996 1447106.8610999994, -648108.5753000006 1447165.1986999996, -648076.5052000005 1447162.7481999993, -648071.1411000006 1447232.9530999996, -648103.2107999995 1447235.4035, -648105.5099 1447205.3157000002, -648233.7895 1447215.1187999994, -648226.1245000008 1447315.4112999998, -647961.5506999996 1447295.1948000006, -647963.8493000008 1447265.1070000008, -647931.7796 1447262.6570999995)))                                                                                                                                                                                                                                                                                                                        │

In [17]:
national.sql(
    """
 SELECT
    CSBID AS csb_id,
    STATEFIPS || CNTYFIPS AS county_geoid,
    CSBACRES AS csb_acres,
    INSIDE_X AS inside_x,
    INSIDE_Y AS inside_y,
    Shape AS geometry
    FROM read_parquet($path)
    ORDER BY csb_id
    LIMIT 10
    """,
    params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
).show()

┌─────────────────┬──────────────┬────────────────────┬──────────────────┬──────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│     csb_id      │ county_geoid │     csb_acres      │     inside_x     │   inside_y   │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         geometry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          │
│     varchar     │   varchar    │       double       │      double      │    double    │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   geometry('epsg:5070')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   │
├─────────────────┼──────────────┼────────────────────┼──────────────────┼──────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 011825000016732 │ 01091        │ 3.8860799977373506 │      762821.1457 │ 1080411.5855 │ MULTIPOLYGON (((762860.8418000005 1080480.6047, 762864.2837000005 1080440.6830000002, 762889.3761 1080442.8463000003, 762894.5390000008 1080382.9638, 762872.0276999995 1080350.8591999998, 762821.8421999998 1080346.5325999996, 762788.3850999996 1080343.6484000003, 762760.7113000005 1080371.4266, 762758.1303000003 1080401.3679, 762755.5493000001 1080431.3092, 762752.1079999991 1080471.2309999997, 762860.8418000005 1080480.6047)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           │
│ 011825000016733 │ 01091        │ 4.1354414318976955 │ 762209.567600001 │ 1080382.0132 │ MULTIPOLYGON (((762236.7355000004 1080487.1475999998, 762245.3330999985 1080387.3427999998, 762270.4257000014 1080389.5043000001, 762273.0051000006 1080359.5626999997, 762253.0707999989 1080297.5184000004, 762194.5207000002 1080292.4747000001, 762169.4277000017 1080290.3134000003, 762155.6732000001 1080450.0012999997, 762203.2789999992 1080484.2654999997, 762236.7355000004 1080487.1475999998)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             │
│ 011825000016734 │ 01091        │  4.155301201460887 │ 762189.740499999 │ 1080096.2448 │ MULTIPOLYGON (((762180.6033000015 1080160.5672000004, 762181.4629999995 1080150.5867999997, 762208.2756999992 1080132.7873, 762225.8643999994 1080124.2478, 762253.1917000003 1080118.3887, 762279.947900001 1080104.3031000001, 762287.8546000011 1080089.3698000005, 762291.2938000001 1080049.4480999997, 762258.6953999996 1080036.5854000002, 762216.8726000004 1080032.9828000003, 762164.9659000002 1080048.6209000004, 762143.7692000009 1080063.2218000004, 762082.0077 1080132.0449, 762071.8656000011 1080151.2018999998, 762113.6878000014 1080154.8037999999, 762122.0522000007 1080155.5241999999, 762155.5100000016 1080158.4058999997, 762180.6033000015 1080160.5672000004)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            │
│ 011825000016735 │ 01091        │ 3.5536504880435715 │ 762340.695700001 │ 1080148.1145 │ MULTIPOLYGON (((762395.4987000003 1080209.2433000002, 762401.5179999992 1080139.3801999995, 762404.0976999998 1080109.4389000004, 762408.3971999995 1080059.5368, 762346.4061000012 1080094.4139999999, 762249.2382000014 1080146.3702999996, 762246.6590000018 1080176.3115999997, 762311.8548000008 1080202.0369999995, 762395.4987000003 1080209.2433000002)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         │
│ 011825000016736 │ 01091        │  6.611995722235357 │      761997.4164 │ 1080088.9009 │ MULTIPOLYGON (((762019.1004999988 1080176.8213, 762108.2745000012 1080076.0571999997, 762113.9191000015 1080054.2788000004, 762080.4609000012 1080051.3973000003, 762057.9457999989 1080019.2948000003, 762061.3838 1079979.3729999997, 762027.9254000001 1079976.4917000001, 762024.4875000007 1080016.4134999998, 761949.2063000016 1080009.9309999999, 761946.6281999983 1080039.8723999998, 761913.1700000018 1080036.9914999995, 761909.7325999998 1080076.9134, 761903.7171999998 1080146.7768, 761927.0918000005 1080168.8984000003, 761959.6900999993 1080181.7598, 761976.4189000018 1080183.2002999997, 762019.1004999988 1080176.8213)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       │
│ 011825000016737 │ 01091        │  4.613569951265608 │ 761384.123599999 │ 1079947.5612 │ MULTIPOLYGON (((761357.6730999984 1080029.3969999999, 761360.2492999993 1079999.4554000003, 761393.7076999992 1080002.3342000004, 761421.377799999 1079974.5519000003, 761449.9068999998 1079936.7890999997, 761457.6361999996 1079846.9645999996, 761444.3418999985 1079805.6030000001, 761419.2476000004 1079803.4437999995, 761416.6713000014 1079833.3853000002, 761415.8125 1079843.3657999998, 761404.8715000004 1079872.5875000004, 761367.1191000007 1079919.6112000002, 761349.5311000012 1079928.1524, 761332.8016999997 1079926.7130000005, 761314.3550999984 1079945.2347999997, 761304.9098000005 1080055.0206000004, 761388.5551000014 1080062.2174000004, 761391.1314000003 1080032.2758, 761357.6730999984 1080029.3969999999)))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          │

In [22]:
tmp_fy = None

tmp_fy = national.sql(
    """
    SELECT
      CSBID AS csb_id,
      CAST(substr(cdl_column, 4) AS SMALLINT) AS year,
    CAST(land_cover_code AS SMALLINT) AS land_cover_code
FROM (
    UNPIVOT (SELECT CSBID, COLUMNS('^CDL\\d{4}$') FROM read_parquet($path)
)
    ON COLUMNS('^CDL\\d{4}$')
    INTO NAME cdl_column VALUE land_cover_code
)
ORDER BY csb_id, year
    LIMIT 1000
    """,
    params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
)

In [25]:
tmp_fy

┌─────────────────┬───────┬─────────────────┐
│     csb_id      │ year  │ land_cover_code │
│     varchar     │ int16 │      int16      │
├─────────────────┼───────┼─────────────────┤
│ 011825000016732 │  2018 │               2 │
│ 011825000016732 │  2019 │               2 │
│ 011825000016732 │  2020 │               2 │
│ 011825000016732 │  2021 │               1 │
│ 011825000016732 │  2022 │               5 │
│ 011825000016732 │  2023 │             176 │
│ 011825000016732 │  2024 │             176 │
│ 011825000016732 │  2025 │             176 │
│ 011825000016733 │  2018 │               5 │
│ 011825000016733 │  2019 │               5 │
│        ·        │    ·  │               · │
│        ·        │    ·  │               · │
│        ·        │    ·  │               · │
│ 011825000016855 │  2024 │             176 │
│ 011825000016855 │  2025 │             176 │
│ 011825000016856 │  2018 │              37 │
│ 011825000016856 │  2019 │              37 │
│ 011825000016856 │  2020 │              37 │
│ 011825000016856 │  2021 │             176 │
│ 011825000016856 │  2022 │              37 │
│ 011825000016856 │  2023 │              37 │
│ 011825000016856 │  2024 │             176 │
│ 011825000016856 │  2025 │             176 │
└─────────────────┴───────┴─────────────────┘
  1000 rows (20 shown)            3 columns

In [ ]:
csb_field.limit(10).show()

In [15]:
national.sql(
    """
    SELECT * EXCLUDE Shape
    FROM read_parquet($path)
    WHERE CSBID = 351825000000001
    """,
    params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
).show()

┌──────────┬─────────────────┬──────────┬───────────────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────────┬──────────┬─────────┬─────────┬──────────┬──────────────┬──────────────┬──────────┬────────────────────┬───────────────────┐
│ OBJECTID │      CSBID      │ CSBYEARS │     CSBACRES      │ CDL2018 │ CDL2019 │ CDL2020 │ CDL2021 │ CDL2022 │ CDL2023 │ CDL2024 │ CDL2025 │ STATEFIPS │ STATEASD │   ASD   │  CNTY   │ CNTYFIPS │   INSIDE_X   │   INSIDE_Y   │ ORIG_FID │    Shape_Length    │    Shape_Area     │
│  int64   │     varchar     │ varchar  │      double       │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  varchar  │ varchar  │ varchar │ varchar │ varchar  │    double    │    double    │  int32   │       double       │      double       │
├──────────┼─────────────────┼──────────┼───────────────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┼─────────┼──────────┼──────────────┼──────────────┼──────────┼────────────────────┼───────────────────┤
│        1 │ 351825000000001 │ 1825     │ 8.014266533798391 │      24 │      24 │      24 │      24 │      24 │       4 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -648193.3343 │ 1447136.6069 │     NULL │ 1094.6718033936615 │ 32432.71572386057 │
└──────────┴─────────────────┴──────────┴───────────────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────────┴──────────┴─────────┴─────────┴──────────┴──────────────┴──────────────┴──────────┴────────────────────┴───────────────────┘

In [16]:
national.sql(
    """
    SELECT * EXCLUDE Shape
    FROM read_parquet($path)
    WHERE CSBID = 351825000000008
    """,
    params={"path": str(NATIONAL_CSB_PARQUET_PATH)},
).show()

┌──────────┬─────────────────┬──────────┬────────────────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬───────────┬──────────┬─────────┬─────────┬──────────┬──────────────┬──────────────┬──────────┬────────────────────┬────────────────────┐
│ OBJECTID │      CSBID      │ CSBYEARS │      CSBACRES      │ CDL2018 │ CDL2019 │ CDL2020 │ CDL2021 │ CDL2022 │ CDL2023 │ CDL2024 │ CDL2025 │ STATEFIPS │ STATEASD │   ASD   │  CNTY   │ CNTYFIPS │   INSIDE_X   │   INSIDE_Y   │ ORIG_FID │    Shape_Length    │     Shape_Area     │
│  int64   │     varchar     │ varchar  │       double       │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  int32  │  varchar  │ varchar  │ varchar │ varchar │ varchar  │    double    │    double    │  int32   │       double       │       double       │
├──────────┼─────────────────┼──────────┼────────────────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼───────────┼──────────┼─────────┼─────────┼──────────┼──────────────┼──────────────┼──────────┼────────────────────┼────────────────────┤
│        8 │ 351825000000008 │ 1825     │ 11.182568883345644 │      24 │      27 │     236 │      24 │      24 │      24 │     152 │     152 │ 35        │ 3530     │ 30      │ Union   │ 059      │ -648139.9377 │ 1446656.0112 │     NULL │ 1218.8649740104102 │ 45254.431722043584 │
└──────────┴─────────────────┴──────────┴────────────────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────────┴──────────┴─────────┴─────────┴──────────┴──────────────┴──────────────┴──────────┴────────────────────┴────────────────────┘

In [26]:
!pwd

/Users/jameshorine/repos/useful-views/crop-sequence-boundaries/sandbox

In [27]:
pl.read_parquet("../useful-views/csb_2025/county.parquet")

shape: (3_087, 5)
┌──────────────┬────────────┬─────────────┬─────────────┬──────────┐
│ county_geoid ┆ state_fips ┆ county_fips ┆ county_name ┆ asd_code │
│ ---          ┆ ---        ┆ ---         ┆ ---         ┆ ---      │
│ str          ┆ str        ┆ str         ┆ str         ┆ str      │
╞══════════════╪════════════╪═════════════╪═════════════╪══════════╡
│ 01001        ┆ 01         ┆ 001         ┆ Autauga     ┆ 0140     │
│ 01003        ┆ 01         ┆ 003         ┆ Baldwin     ┆ 0150     │
│ 01005        ┆ 01         ┆ 005         ┆ Barbour     ┆ 0160     │
│ 01007        ┆ 01         ┆ 007         ┆ Bibb        ┆ 0130     │
│ 01009        ┆ 01         ┆ 009         ┆ Blount      ┆ 0120     │
│ …            ┆ …          ┆ …           ┆ …           ┆ …        │
│ 56037        ┆ 56         ┆ 037         ┆ Sweetwater  ┆ 5640     │
│ 56039        ┆ 56         ┆ 039         ┆ Teton       ┆ 5630     │
│ 56041        ┆ 56         ┆ 041         ┆ Uinta       ┆ 5630     │
│ 56043        ┆ 56         ┆ 043         ┆ Washakie    ┆ 5610     │
│ 56045        ┆ 56         ┆ 045         ┆ Weston      ┆ 5620     │
└──────────────┴────────────┴─────────────┴─────────────┴──────────┘

In [28]:
pl.read_parquet("../useful-views/csb_2025/csb_field_year.parquet")

shape: (127_784_760, 3)
┌─────────────────┬──────┬─────────────────┐
│ csb_id          ┆ year ┆ land_cover_code │
│ ---             ┆ ---  ┆ ---             │
│ str             ┆ i16  ┆ i16             │
╞═════════════════╪══════╪═════════════════╡
│ 011825000016732 ┆ 2018 ┆ 2               │
│ 011825000016732 ┆ 2019 ┆ 2               │
│ 011825000016732 ┆ 2020 ┆ 2               │
│ 011825000016732 ┆ 2021 ┆ 1               │
│ 011825000016732 ┆ 2022 ┆ 5               │
│ …               ┆ …    ┆ …               │
│ 561825015410849 ┆ 2021 ┆ 36              │
│ 561825015410849 ┆ 2022 ┆ 36              │
│ 561825015410849 ┆ 2023 ┆ 36              │
│ 561825015410849 ┆ 2024 ┆ 36              │
│ 561825015410849 ┆ 2025 ┆ 121             │
└─────────────────┴──────┴─────────────────┘

In [ ]:
fy_p = None
fy_p = pl.read_parquet("../useful-views/csb_2025/c")